-- Auto-generated by scripts/gen-blog-seed.ts. Do not edit by hand.
INSERT OR REPLACE INTO blog_posts
  (slug, title, excerpt, content, author, featured_image, tags, category, published, published_at, created_at, updated_at)
VALUES ('buckeye-beer-engine-road-trip-ohio-passport-2026', 'Buckeye Beer Engine Launches 2026 Road Trip Around Ohio Passport', 'Lakewood''s Buckeye Beer Engine is pouring two beers from 20 Ohio breweries all summer long — a $20 passport celebrating the Buckeye State''s independent brewing scene.', 'For years, Buckeye Beer Engine has been regarded as one of Ohio''s premier destinations for craft beer lovers, earning a reputation for pouring some of the state''s most sought-after beers and maintaining one of the deepest draft selections around.

Now, the Lakewood institution is looking to reinforce that reputation while simultaneously shining a spotlight on Ohio''s independent brewing scene and encouraging beer tourism across the Buckeye State.

## A New Twist on an Old Idea

Launching Monday, June 8, Buckeye Beer Engine''s **2026 Road Trip Around Ohio Passport** will feature beers from 20 breweries representing every corner of the state. It''s a new twist on an old idea, borrowing heavily from things like Winking Lizard Tavern''s long-running World Tour of Beers, but giving it a distinctly local flavor.

For **$20**, participants can sample two designated beers from each brewery throughout the summer, with a finisher T-shirt awaiting those who complete the passport and additional swag opportunities available for those who conquer all 40 featured beers.

## Participating Breweries

🍻 **Hoppin'' Frog Brewery** (Akron)

🍻 **Land-Grant Brewing Company** (Columbus)

🍻 **Gemüt Biergarten** (Columbus)

🍻 **Crooked Pecker Brewing Company** (Chagrin Falls)

🍻 **Eleventhree Brewing** (Chardon)

🍻 **The Phoenix Brewing Company** (Mansfield)

🍻 **Sonder Brewing** (Mason)

🍻 **Streetside Brewery** (Cincinnati)

🍻 **Jackie O''s Brewery** (Athens)

🍻 **JAFB Wooster Brewery** (Wooster)

🍻 **8th Day Brewing Co.** (Auburn Twp)

🍻 **Darkroom Brewing Co.** (Geneva)

🍻 **Branch & Bone Artisan Ales** (Dayton)

🍻 **Three Tigers Brewing Company** (Granville)

🍻 **Inside the Five Brewing Company** (Perrysburg/Sylvania)

🍻 **Oncore Brewing** (Swanton)

🍻 **HiHO Brewing Company** (Cuyahoga Falls)

🍻 **Bell Tower Brewing Co.** (Kent)

🍻 **Seventh Son Brewing** (Columbus)

🍻 **Rockmill Brewery** (Lancaster)

## First Five on Tap

The first five breweries to hit the taps Monday will be **Hoppin'' Frog, Streetside, HiHO, Three Tigers and Gemüt Biergarten**, with new beers rotating in as kegs are depleted throughout the summer.

It''s a unique opportunity to sample breweries from across Ohio in one location — and perhaps find inspiration for your next brewery road trip.

> Which one of these breweries is new to you, and who are you trying first?

Plan your own Road Trip Around Ohio with Ohio Beer Path — map out the participating breweries, build a route, and turn your passport stamps into a full-state adventure.', 'Ohio Beer Path', 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=1200', 'Events, Passport, Buckeye Beer Engine, Lakewood, Beer Tourism, 2026', 'Events', 1, '2026-06-06T12:00:00.000Z', '2026-06-06T12:00:00.000Z', '2026-06-06T12:00:00.000Z');

INSERT OR REPLACE INTO blog_posts
  (slug, title, excerpt, content, author, featured_image, tags, category, published, published_at, created_at, updated_at)
VALUES ('best-ohio-ipa-breweries-2024', 'The 10 Best Ohio Breweries for IPA Lovers in 2024', 'From hazy New England-style to crisp West Coast IPAs, these Ohio breweries are pushing the boundaries of hop-forward brewing.', 'Ohio has quietly become one of the best states in the Midwest for craft beer, and IPA lovers have plenty of reasons to celebrate. From Cleveland to Cincinnati, breweries are crafting everything from hazy juice bombs to classic West Coast bitters.

## What Makes Ohio IPAs Special?

Ohio brewers benefit from access to fresh Great Lakes water and a growing community of hop suppliers. Many breweries have established relationships with farms in the Pacific Northwest, ensuring they get the freshest hops for their brews.

### Our Top Picks

**1. Great Lakes Brewing Company** - Cleveland''s legendary brewery has been perfecting their hop game since 1988. Their Commodore Perry IPA remains a benchmark for the style.

**2. Fat Head''s Brewery** - Known for Head Hunter IPA, which has won numerous awards and is considered one of the best IPAs in the country.

**3. Platform Beer Co.** - Their rotating IPA series showcases the latest hop varieties and brewing techniques.

> "Ohio''s craft beer scene has exploded in the last decade, and our IPAs can compete with anyone in the country." - Local brewer

### The Hazy Revolution

Northeast Ohio has embraced the hazy IPA trend, with breweries like Masthead and Noble Beast creating silky, juicy interpretations that rival the best from New England.

## Plan Your IPA Tour

Use Ohio Beer Path to create your perfect IPA-focused brewery tour. Filter by region and add your favorites to your itinerary for an unforgettable hop-filled adventure.', 'Ohio Beer Path', 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=1200', 'IPA, Best Of, 2024, Craft Beer', 'Guides', 1, '2026-06-05T12:00:00.000Z', '2026-06-05T12:00:00.000Z', '2026-06-05T12:00:00.000Z');

INSERT OR REPLACE INTO blog_posts
  (slug, title, excerpt, content, author, featured_image, tags, category, published, published_at, created_at, updated_at)
VALUES ('cleveland-craft-beer-weekend-guide', 'The Ultimate Cleveland Craft Beer Weekend Guide', 'Spend 48 hours exploring Cleveland''s thriving craft beer scene, from Ohio City to Tremont and beyond.', 'Cleveland''s craft beer scene is one of the most exciting in the Midwest. With over 40 breweries in the greater Cleveland area, planning a beer-focused weekend can feel overwhelming. Here''s our guide to making the most of 48 hours in the Forest City.

## Day 1: Ohio City

Start your morning with coffee at Rising Star before diving into Ohio City''s brewery row.

### Must-Visit Spots

**Great Lakes Brewing Company** - Start at the godfather of Cleveland craft beer. Tour the brewery, then grab lunch at their brewpub.

**Market Garden Brewery** - Just across the street, Market Garden offers a more modern vibe with excellent food pairings.

**Hansa Brewery** - For something different, check out Hansa''s German-style lagers and traditional recipes.

## Day 1 Evening: Downtown & Flats

As night falls, head downtown to Platform Beer Co. for their innovative brews, then explore the revitalized Flats district.

## Day 2: Tremont & Beyond

**Tremont Taphouse** - Not a brewery, but one of the best beer bars in the state with 100+ taps.

**Bookhouse Brewing** - A cozy neighborhood spot with excellent IPAs and a welcoming atmosphere.

### Pro Tips

- Use rideshare services or designate a driver
- Many breweries offer flights - great for sampling
- Check for live music on weekends
- Book brewery tours in advance during peak season

Make sure to check each brewery''s hours before visiting, and use Ohio Beer Path to plan your route!', 'Ohio Beer Path', 'https://images.unsplash.com/photo-1559526324-593bc073d938?w=1200', 'Cleveland, Weekend Guide, Itinerary', 'Guides', 1, '2026-06-04T12:00:00.000Z', '2026-06-04T12:00:00.000Z', '2026-06-04T12:00:00.000Z');

INSERT OR REPLACE INTO blog_posts
  (slug, title, excerpt, content, author, featured_image, tags, category, published, published_at, created_at, updated_at)
VALUES ('ohio-beer-week-2024-preview', 'Ohio Beer Week 2024: What to Expect', 'Get ready for the biggest celebration of Ohio craft beer with events happening across the state.', 'Ohio Beer Week is back and bigger than ever! This annual celebration of Ohio craft beer brings together breweries, bars, and beer lovers from across the state for a week of special releases, tap takeovers, and collaborative events.

## When Is Ohio Beer Week?

Mark your calendars for the third week of July. Events will be happening throughout the week, with the biggest celebrations on Friday and Saturday.

## Featured Events

### Kickoff Party
The week starts with a massive kickoff party featuring 50+ Ohio breweries pouring their best. Location to be announced.

### Collaboration Brew Day
Watch as rival breweries come together to create special one-off beers. Past collaborations have produced some incredible results.

### Beer and Food Pairings
Participating restaurants will offer special menus designed to pair with local craft beers.

> "Ohio Beer Week is the highlight of our year. The collaboration between breweries shows what makes our state''s beer scene so special." - Ohio Craft Brewers Association

## How to Participate

- Follow your favorite Ohio breweries on social media for announcements
- Sign up for brewery newsletters for early access to special releases
- Plan your route using Ohio Beer Path
- Consider booking accommodations near brewery districts

Stay tuned for the full event schedule coming soon!', 'Ohio Beer Path', 'https://images.unsplash.com/photo-1575037614876-c38a4d44f5b8?w=1200', 'Events, Ohio Beer Week, 2024', 'Events', 1, '2026-06-03T12:00:00.000Z', '2026-06-03T12:00:00.000Z', '2026-06-03T12:00:00.000Z');

INSERT OR REPLACE INTO blog_posts
  (slug, title, excerpt, content, author, featured_image, tags, category, published, published_at, created_at, updated_at)
VALUES ('dog-friendly-ohio-breweries', '15 Dog-Friendly Ohio Breweries Where Your Pup Is Welcome', 'Bring your four-legged friend along for brewery hopping at these pet-friendly Ohio spots.', 'Who says you can''t enjoy craft beer with your best friend? Ohio has dozens of dog-friendly breweries where your pup can join you for a pint. Here are our favorites.

## Cleveland Area

**1. Bookhouse Brewing** - Cozy patio perfect for dogs and their humans
**2. Collision Bend Brewing** - Spacious outdoor area with river views
**3. Terrestrial Brewing** - Dog-friendly taproom with a relaxed vibe

## Columbus Area

**4. Land-Grant Brewing** - Large outdoor space, often hosts dog-themed events
**5. Seventh Son Brewing** - Italian Village location welcomes well-behaved dogs
**6. Hoof Hearted Brewery** - Their Marengo location has plenty of space

## Cincinnati Area

**7. MadTree Brewing** - Expansive outdoor area, dog water bowls provided
**8. Rhinegeist** - Dog-friendly taproom in historic brewery building
**9. Fifty West Brewing** - Beautiful outdoor seating by the river

## Tips for Brewery Hopping with Dogs

- Always call ahead to confirm dog policies
- Bring water and a bowl for your pup
- Keep your dog on a leash
- Be mindful of other patrons
- Clean up after your dog
- Know your dog''s limits in social situations

Many of these breweries even have special dog treats available. Use the Ohio Beer Path amenity filter to find more dog-friendly spots near you!', 'Ohio Beer Path', 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=1200', 'Dog Friendly, Guides, Pet Friendly', 'Guides', 1, '2026-06-02T12:00:00.000Z', '2026-06-02T12:00:00.000Z', '2026-06-02T12:00:00.000Z');
