// Generates infra/seed-blog-posts.sql from the canonical sampleBlogPosts array
// so the live D1 blog_posts table stays in sync with the committed code.
// Usage: npx tsx scripts/gen-blog-seed.ts
import { sampleBlogPosts } from '../src/templates/blog';
import { writeFileSync } from 'node:fs';

const q = (v: string | number | undefined | null): string => {
  if (v === undefined || v === null) return 'NULL';
  if (typeof v === 'number') return String(v);
  return `'${v.replace(/'/g, "''")}'`;
};

// Assign descending dates so the newest sample (index 0) sorts first.
const base = Date.parse('2026-06-06T12:00:00.000Z');
const rows = sampleBlogPosts.map((p, i) => {
  // Deterministic descending dates by array order so index 0 is the newest
  // (featured) post. Ignores sample posts' runtime new Date() values.
  const createdAt = new Date(base - i * 86400000).toISOString();
  return `INSERT OR REPLACE INTO blog_posts
  (slug, title, excerpt, content, author, featured_image, tags, category, published, published_at, created_at, updated_at)
VALUES (${q(p.slug)}, ${q(p.title)}, ${q(p.excerpt)}, ${q(p.content)}, ${q(p.author)}, ${q(p.featured_image)}, ${q(p.tags)}, ${q(p.category)}, ${q(p.published)}, ${q(createdAt)}, ${q(createdAt)}, ${q(createdAt)});`;
});

const sql = `-- Auto-generated by scripts/gen-blog-seed.ts. Do not edit by hand.\n${rows.join('\n\n')}\n`;
writeFileSync(new URL('../infra/seed-blog-posts.sql', import.meta.url), sql);
console.log(`Wrote ${rows.length} blog posts to infra/seed-blog-posts.sql`);
